---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: vmware_desktop

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: mojave-usevars
    groups:
      - usevars
    box: msl/macos_mojave_10.14
    memory: 2048
    cpus: 2
    config_options:
      synced_folder: False
  - name: mojave-novars
    groups:
      - novars
    box: msl/macos_mojave_10.14
    memory: 2048
    cpus: 2
    config_options:
      synced_folder: False

provisioner:
  name: ansible
  inventory:
    group_vars:
      usevars:
        terminal_default_profile: "Ulmer"
        terminal_add_profiles:
          - "Ulmer.terminal"
          - "Ulmer Pro.terminal"
  log: True

verifier:
  name: ansible
  enabled: False
