---
dependency:
  name: galaxy

driver:
  name: vagrant

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: macos-usevars
    groups:
      - usevars
    box: macinbox
  - name: macos-novars
    groups:
      - novars
    box: macinbox

provisioner:
  name: ansible
  inventory:
    group_vars:
      usevars:
        terminal_default_profile: "Ulmer"
        terminal_add_profiles:
          - "Ulmer.terminal"
          - "Ulmer Pro.terminal"
  log: True

verifier:
  name: ansible
  enabled: False
